# numpy has several functions including:
# -- np.sum() 
# -- np.mean()
# -- np.median()
# -- np.std()
# -- np.var()
# -- np.min()
# -- np.max()
# -- np.argmin()
# -- np.argmax()
# -- np.unique()
# -- np.sort()
# -- np.concatenate()
# --np.array()
# -- np.reshape()
# -- np.transpose()
# -- np.shape()